### ISSUE TITLE
[Проблема] Не удаётся запустить проект следуя инструкциям по readme.md

### ISSUE THREAD

**Issue by airyng** [PavelShar/anilibrix#67]
Хочу попробовать себя в разработке фичи для приложения как сторонний контрибутор. Произвел следующие действия:

1. Склонировал репозиторий.
2. Используя nvm переключил версию nodejs на ту, что указана в readme.md. 
3. Запустил команду `yarn`.  Модули установились без ошибок.
4. Запустил команду `yarn run serve`. Появляется следующая ошибка:

```
Executing task: yarn run serve 

yarn run v1.22.19
$ node .electron-vue/dev-runner.js
## There is an issue with `node-fibers` ##
`E:\projects\anilibrix\node_modules\fibers\bin\win32-x64-83\fibers.node` is missing.

Try running this to fix the issue: C:\Program Files\nodejs\node.exe E:\projects\anilibrix\node_modules\fibers/build
Error: Cannot find module 'E:\projects\anilibrix\node_modules\fibers\bin\win32-x64-83\fibers'
Require stack:
- E:\projects\anilibrix\node_modules\fibers\fibers.js
- E:\projects\anilibrix\.electron-vue\webpack.renderer.config.js
- E:\projects\anilibrix\.electron-vue\dev-runner.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\projects\anilibrix\node_modules\fibers\fibers.js:14:39)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\projects\anilibrix\.electron-vue\webpack.renderer.config.js:50:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
E:\projects\anilibrix\node_modules\fibers\fibers.js:23
                throw new Error('Missing binary. See message above.');
                ^

Error: Missing binary. See message above.
    at Object.<anonymous> (E:\projects\anilibrix\node_modules\fibers\fibers.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\projects\anilibrix\.electron-vue\webpack.renderer.config.js:50:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\projects\anilibrix\.electron-vue\dev-runner.js:13:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Похоже, главная проблема, это ненайденный файл `E:\projects\anilibrix\node_modules\fibers\bin\win32-x64-83\fibers.node`. Посмотрел в node_modules и действительно нет всей директории win32-x64-83. Хотя директории для других ОС имеются.
Как с этим бороться?

Доп инфо:
```
node -v
v14.18.0
```

**Comment by pavloniym** [comment]
Здравствуйте.
Попробуйте собрать проект не с master ветки (там не рабочий код), а с последней версии

**Comment by airyng** [comment]
Перешел на коммит с тегом последней версии "v1.4.3".
Запустил `yarn`
После этого вылезла ошибка, которая требовала установить Visual Studio и node-gyp.
Это я выполнил. Попробовал повторить команду.

И теперь у меня другая ошибка:
```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[6/10] ⠁ electron
[10/10] ⠁ node-sass
[-/10] ⠁ waiting...
[9/10] ⠁ fibers
error E:\projects\anilibrix\node_modules\fibers: Command failed.
Exit code: 1
Command: node build.js || nodejs build.js
Arguments: 
Directory: E:\projects\anilibrix\node_modules\fibers
Output:
E:\projects\anilibrix\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "" rebuild --release )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.18.0 | win32 | x64
gyp info find Python using Python version 3.11.4 found at "C:\Users\admin\AppData\Local\Programs\Python\Python311\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "D:\programs\VisualStudio\DevEnv"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (D:\programs\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at D:\programs\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\programs\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at D:\programs\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at D:\programs\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at D:\programs\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at D:\programs\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd E:\projects\anilibrix\node_modules\fibers
gyp ERR! node -v v14.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
```
Судя по всему, не хватает переменных окружения
```
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
```
Их надо задать вручную? Если так, то что указывать для `msvs_version`?

**Comment by Viiprogrammer** [comment]
Не может найти VS. А должно. Это возможно проблема с самим node-gyp. Точно установленны Build tools для C/C++ ?

**Comment by airyng** [comment]
Установлены такие пакеты с названием build tools.
![image](https://github.com/pavloniym/anilibrix/assets/14352077/afcee7aa-98f9-4383-acd8-71f1e02d25d8)
Версия VS 2022 - 17.7.6

**Comment by Viiprogrammer** [comment]
Есть вероятность того что оно не видит новую версию.  Были какие-то похожие баги, вот недавно на CI/CD. Нужно пробовать обновлять node-gyp до последней.

Что-то вроде `npm i -g node-gyp`,  а лучше глянуть  ласт версию на npm и вписать её принудительно `npm i -g node-gyp@version`.

Ну и node лучше убедится что 14, ибо выше оно обычно никогда не собиралось. 

Можешь попробовать ради эксперемента инстальнуть вот отсюда https://github.com/AnimeHaze/anilibrix,  но там не думаю что будет большая разница. Не сильно у меня в зависимости разницы много.
